project:
  type: website
  output-dir: docs

website:
  title: "Lele Liao | Data Analyst"

  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: presentation.qmd
        text: Presentations
      - href: resume.qmd
        text: Resume

    right:
      - icon: github
        href: https://github.com/rsm-l2liao
      - icon: linkedin
        href: https://www.linkedin.com/in/lele-liao-134340/

  page-footer:
    center: |
      © 2026 Lele Liao · Portfolio

format:
  html:
    theme:
      light: cosmo
      dark: darkly

    css:
      - styles.css

    toc: false

    code-copy: true
    code-fold: false

    smooth-scroll: true
    link-external-newwindow: true

    page-layout: article
